apiVersion: v1
kind: Service
metadata:
  name: nexusai-headless-service
  labels:
    app: nexusai
spec:
  clusterIP: None
  selector:
    app: nexusai
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
