apiVersion: v1
kind: Service
metadata:
  name: nexusai-service
  labels:
    app: nexusai
spec:
  type: NodePort
  selector:
    app: nexusainew
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
