apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-5g
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  mountOptions:
    - hard
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - timeo=600
    - retrans=2
    - noresvport
  nfs:
    path: /pod1
    server: fs-0d2c10cff9d201780.efs.us-east-1.amazonaws.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-5g
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: pv-5g
  resources:
    requests:
      storage: 5Gi
