apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexusai-deployment
  labels:
    app: nexusainew
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nexusainew
  template:
    metadata:
      labels:
        app: nexusainew
    spec:
      containers:
      - name: nexusai
        image: priniel/nexusai:1.0
        ports:
        - containerPort: 80
